# Generated by Django 4.2.7 on 2025-09-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_advertisement_checkuppackage_contactmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='checkuppackage',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
