# Generated by Django 4.2.7 on 2025-10-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appointment_status_checkuppackage_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkuppackage',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
